#getting the base image from ubuntu 16.04
FROM ubuntu:16.04

MAINTAINER anilsree <avskr.6@gmail.com>

RUN apt-get update

RUN apt-get install telnet -y && apt-get install curl -y && apt-get install ffmpeg -y

CMD ["echo", "Installed requested packages!"]


